services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "3001:3001"
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/botanika
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=botanika
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=botanika
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/api/database/db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
