services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file: .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=botanika
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/api/database/db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql
    restart: unless-stopped

volumes:
  postgres_data: