export enum BotanikaFeature {
    GoogleSearch = "Google Search",
    OpenAI = "OpenAI",
    Groq = "Groq",
    Ollama = "Ollama",
    Azure = "Azure",
    OpenRouter = "OpenRouter",
    ElevenLabs = "ElevenLabs",
    RevAi = "RevAi",
    Lmnt = "LMNT",
    Hume = "Hume",
    Deepgram = "Deepgram",
    Gladia = "Gladia",
    AssemblyAI = "AssemblyAI",
    Fal = "Fal",
}
